# Generated by Django 6.0.5 on 2026-06-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
