# Generated by Django 6.0.5 on 2026-06-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('min_deposit_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('max_booking_days', models.PositiveIntegerField(default=30)),
                ('auto_approve_bookings', models.BooleanField(default=False)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('payment_gateway_mode', models.CharField(default='SANDBOX', max_length=20)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('support_email', models.EmailField(default='support@sharehub.local', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Platform settings',
            },
        ),
    ]
