# Generated by Django 6.0.5 on 2026-06-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='payment_gateway_mode',
            field=models.CharField(choices=[('SANDBOX', 'Sandbox'), ('LIVE', 'Live'), ('DISABLED', 'Disabled')], default='SANDBOX', max_length=20),
        ),
    ]
